name: layout
description: >-
  Sample app from "Building Layouts", https://docs.flutter.dev/ui/layout.
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  infinite_scroll_pagination: ^4.0.0
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  audioplayers: ^6.1.0
  image_picker: ^1.1.2

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/lake.jpg
    - assets/sounds/drum-roll.wav
    - assets/sounds/bass-hit.wav
    - assets/sounds/song.mp3
